language: script

env:
  global:
     CF_TARGET_URL="https://api.stage1.ng.bluemix.net"

script: bash -n *.sh


deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy_rollup.sh
    on:
      all_branches: true
